"""Coordinates one chat turn Turn: status updates -> mock generation -> persist."""

from __future__ import annotations

import uuid
import asyncio
from collections.abc import AsyncIterator

from supabase import AsyncClient

from app.auth.dependencies import CurrentUser
from app.chat.messages import text_from_parts
from app.chat.streaming import (
    stream_stubbed_answer,
    stream_status,
    sse_event,
)
from app.database.chats import append_grounded_turn
from app.schemas.chat import UIMessage, TextPart


async def run_turn(
    *,
    client: AsyncClient,
    thread_id: uuid.UUID,
    user: CurrentUser,
    user_message: UIMessage,
    thread_title: str,
) -> AsyncIterator[str]:
    query = text_from_parts(user_message.parts).strip()
    if not query:
        yield sse_event({"type": "error", "errorText": "User message is empty."})
        return

    # 1. Yield simulated search steps
    async for event in stream_status("searching", "Searching SEC filings..."):
        yield event
    await asyncio.sleep(0.6)

    async for event in stream_status("reading", "Reading source passages..."):
        yield event
    await asyncio.sleep(0.4)

    async for event in stream_status("verifying", "Verifying citations..."):
        yield event
    await asyncio.sleep(0.4)

    # 2. Yield text deltas
    message_id = str(uuid.uuid4())
    async for event in stream_stubbed_answer(query, message_id):
        yield event

    # 3. Assemble and save turning record in background
    reply_content = (
        f"Hello! I am your Document Copilot research assistant. "
        f"You asked: '{query}'. "
        f"In later implementation phases, this space will contain a fully grounded answer "
        f"generated by our PydanticAI model, complete with inline interactive citations "
        f"mapping directly to indexed SEC filing database chunks. Everything is working correctly."
    )
    
    assistant_message = UIMessage(
        id=message_id,
        role="assistant",
        parts=[TextPart(text=reply_content)]
    )

    await append_grounded_turn(
        client=client,
        thread_id=thread_id,
        user_message=user_message,
        assistant_message=assistant_message,
        thread_title=thread_title
    )
