"""AI SDK-compatible SSE streaming for stubbed grounded assistant replies."""

from __future__ import annotations

import json
import uuid
import asyncio
from collections.abc import AsyncIterator

from app.schemas.chat import UIMessage, TextPart


def sse_event(payload: dict[str, object]) -> str:
    return f"data: {json.dumps(payload, separators=(',', ':'), default=str)}\n\n"


async def stream_status(stage: str, message: str) -> AsyncIterator[str]:
    yield sse_event({
        "type": "data-status",
        "data": {
            "stage": stage,
            "message": message
        }
    })


async def stream_stubbed_answer(query: str, message_id: str) -> AsyncIterator[str]:
    yield sse_event({"type": "start", "messageId": message_id})
    yield sse_event({"type": "text-start", "id": message_id})

    reply_content = (
        f"Hello! I am your Document Copilot research assistant. "
        f"You asked: '{query}'. "
        f"In later implementation phases, this space will contain a fully grounded answer "
        f"generated by our PydanticAI model, complete with inline interactive citations "
        f"mapping directly to indexed SEC filing database chunks. Everything is working correctly."
    )

    for word in reply_content.split(" "):
        yield sse_event({
            "type": "text-delta",
            "id": message_id,
            "delta": f"{word} "
        })
        await asyncio.sleep(0.06)

    yield sse_event({"type": "text-end", "id": message_id})
    yield sse_event({"type": "finish"})
