server {
    listen 3000;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # SPA Router fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Healthcheck route
    location /health {
        return 200 'ok';
    }
}